apiVersion: v1
kind: ReplicationController
metadata:
  name: myjenkins-rc
spec:
   replicas: 3
   selector:
     app: myjenkins-pod
   template:
    metadata:
      labels:
         app: myjenkins-pod
    spec:
         containers:
         - name: myjenkins-container
           image: jenkins:latest
           ports:
           - containerPort: 8080


                       