apiVersion: v1
kind: Service
metadata:
  name: sonar-svc
  labels:
     app: sonar-pod
spec:
  type: NodePort
  ports:
    - port: 9000
      nodePort: 30001
      protocol: TCP
  selector:
     app: sonar-pod