apiVersion: v1
kind: ReplicationController
metadata:
  name: sonar-rc
spec:
    replicas: 3
    selector:
      app: sonar-pod
    template:
     metadata:
       labels:
         app: sonar-pod
     spec:
        containers:
          - name: sonar-container
            image: sonarqube
            ports:
              - containerPort: 9000
