apiVersion: v1
kind: Service
metadata:
  name: myterraform-svc
  labels:
    app: myterraform-pod
spec:
  type: NodePort
  ports:
    - port: 8800
      nodePort: 30001
      protocol: TCP
  selector:
    app: myterraform-pod